sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tGrtpWz8cwJnr2vrDm9
    access-key-secret: WnGupK1qpMSingMlNInodISM7TN3qH
    bucket-name: web-tlias-testwang
  redis:
    host: localhost
    port: 6379